name = "studiobuku"
main = "server.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "studiobuku-db"
database_id = "6d8fca8c-6bc8-4b88-9201-5a0ba5a34a13" # Ganti dengan database_id dari wrangler d1 create

[vars]
NODE_VERSION = "18"
