-- ==========================================================
-- STUDIO BUKU DATABASE SCHEMA & SEED DATA (Cloudflare D1)
-- Database Name: studiobuku-db
-- Total Projects: 60 | Total Chapters: 480
-- ==========================================================

CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  genre TEXT,
  synopsis TEXT,
  createdAt TEXT NOT NULL,
  isPrivate INTEGER NOT NULL DEFAULT 0,
  ownerId TEXT,
  ownerName TEXT,
  coAuthors TEXT
);

CREATE TABLE IF NOT EXISTS chapters (
  id TEXT PRIMARY KEY,
  projectId TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  content TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'draft',
  lastEditedBy TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS authors (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  avatar TEXT,
  color TEXT
);

CREATE TABLE IF NOT EXISTS glossary (
  id TEXT PRIMARY KEY,
  projectId TEXT NOT NULL,
  term TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Karakter',
  definition TEXT NOT NULL,
  aliases TEXT,
  updatedAt TEXT NOT NULL,
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ideas (
  id TEXT PRIMARY KEY,
  projectId TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  category TEXT NOT NULL DEFAULT 'Plot',
  authorId TEXT NOT NULL,
  pinned INTEGER NOT NULL DEFAULT 0,
  createdAt TEXT NOT NULL,
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS logs (
  id TEXT PRIMARY KEY,
  projectId TEXT NOT NULL,
  chapterId TEXT,
  chapterTitle TEXT,
  authorName TEXT NOT NULL,
  action TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS annotations (
  id TEXT PRIMARY KEY,
  projectId TEXT NOT NULL,
  chapterId TEXT NOT NULL,
  chapterTitle TEXT,
  text TEXT NOT NULL,
  authorName TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  resolved INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE
);

-- ==========================================================
-- SEED DATA PENULIS (4 PENULIS)
-- ==========================================================
INSERT OR REPLACE INTO authors (id, name, role, avatar, color) VALUES ('auth_1', 'Rian Hidayat', 'Penulis Utama', '👨‍💻', 'bg-emerald-500');
INSERT OR REPLACE INTO authors (id, name, role, avatar, color) VALUES ('auth_2', 'Kirana Maharani', 'Penulis Studio', '👩‍🎨', 'bg-indigo-500');
INSERT OR REPLACE INTO authors (id, name, role, avatar, color) VALUES ('auth_3', 'Bagus Setiawan', 'Riset & Peneliti', '🎓', 'bg-amber-500');
INSERT OR REPLACE INTO authors (id, name, role, avatar, color) VALUES ('auth_4', 'Siti Rahmania', 'Editor Naskah', '📚', 'bg-rose-500');

-- ==========================================================
-- SEED DATA 60 PROYEK NASKAH
-- ==========================================================
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_1', 'Gema Di Ujung Senja', 'Novel Fiksi Psikologis & Perjalanan Dua Jiwa', 'Fiksi / Drama', 'Naskah "Gema Di Ujung Senja" — Novel Fiksi Psikologis & Perjalanan Dua Jiwa. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-30T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_2', 'Lembayung Kotabaru', 'Misteri Berkas Tua 1965', 'Misteri & Detektif', 'Naskah "Lembayung Kotabaru" — Misteri Berkas Tua 1965. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-29T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_3', 'Sandi Dibalik Candi', 'Perjalanan Arkeologis Di Lembah Progo', 'Akademik & Riset', 'Naskah "Sandi Dibalik Candi" — Perjalanan Arkeologis Di Lembah Progo. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-28T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_4', 'Bunga Rumput Samudra', 'Antologi Puisi & Narasi Pesisir', 'Biografi & Memoar', 'Naskah "Bunga Rumput Samudra" — Antologi Puisi & Narasi Pesisir. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-27T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_5', 'Pelaut Malam Dan Bintang', 'Novel Fiksi Sejarah Bahari', 'Fiksi / Sejarah', 'Naskah "Pelaut Malam Dan Bintang" — Novel Fiksi Sejarah Bahari. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-26T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_6', 'Cahaya Di Balik Kabut', 'Pengembangan Diri & Ketenangan Jiwa', 'Pengembangan Diri', 'Naskah "Cahaya Di Balik Kabut" — Pengembangan Diri & Ketenangan Jiwa. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-25T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_7', 'Detektif Batavia 1920', 'Penyelewengan Di Pelabuhan Tanjung Priok', 'Misteri & Detektif', 'Naskah "Detektif Batavia 1920" — Penyelewengan Di Pelabuhan Tanjung Priok. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-24T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_8', 'Riset Kecerdasan Buatan & Etika', 'Tinjauan Etis AI Dalam Pendidikan Tinggi', 'Sains & Teknologi', 'Naskah "Riset Kecerdasan Buatan & Etika" — Tinjauan Etis AI Dalam Pendidikan Tinggi. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-23T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_9', 'Jejak Langkah Di Pasar Beringharjo', 'Etnografi Sosial Pedagang Jamu Tradisional', 'Sosiologi & Budaya', 'Naskah "Jejak Langkah Di Pasar Beringharjo" — Etnografi Sosial Pedagang Jamu Tradisional. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-22T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_10', 'Rahasia Kedai Kopi Tua', 'Perbincangan Hangat Di Sudut Kota', 'Fiksi / Drama', 'Naskah "Rahasia Kedai Kopi Tua" — Perbincangan Hangat Di Sudut Kota. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-21T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_11', 'Babad Serayu Dan Sungai Jiwa', 'Kisah Peradaban Lembah Sungai Serayu', 'Sejarah & Kebudayaan', 'Naskah "Babad Serayu Dan Sungai Jiwa" — Kisah Peradaban Lembah Sungai Serayu. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-20T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_12', 'Menulis Tanpa Rasa Takut', 'Panduan Menembus Blok Kreatif Penulis Naskah', 'Pengembangan Diri', 'Naskah "Menulis Tanpa Rasa Takut" — Panduan Menembus Blok Kreatif Penulis Naskah. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-19T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_13', 'Bayang-Bayang Di Atas Candi Prambanan', 'Teka-Teki Arsitektur Zaman Mataram Kuno', 'Misteri & Detektif', 'Naskah "Bayang-Bayang Di Atas Candi Prambanan" — Teka-Teki Arsitektur Zaman Mataram Kuno. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-18T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_14', 'Logika Dan Logika Hati', 'Dialektika Filsafat Modern Dan Realitas', 'Filsafat & Riset', 'Naskah "Logika Dan Logika Hati" — Dialektika Filsafat Modern Dan Realitas. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-17T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_15', 'Jejak Pengembara Parahyangan', 'Memoar Perjalanan Di Pegunungan Bandung Selatan', 'Biografi & Memoar', 'Naskah "Jejak Pengembara Parahyangan" — Memoar Perjalanan Di Pegunungan Bandung Selatan. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-16T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_16', 'Nyanyian Angin Kotagede', 'Antologi Prosa Liris Pengrajin Perak', 'Puisi & Prosa', 'Naskah "Nyanyian Angin Kotagede" — Antologi Prosa Liris Pengrajin Perak. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-15T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_17', 'Dilema Dosen Muda', 'Catatan Humoris Di Ruang Dosen Dan Kelas', 'Komedi & Satir', 'Naskah "Dilema Dosen Muda" — Catatan Humoris Di Ruang Dosen Dan Kelas. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-14T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_18', 'Penjaga Gerbang Merapi', 'Kisah Mitos Dan Sains Di Lereng Gunung', 'Fantasi & Folklor', 'Naskah "Penjaga Gerbang Merapi" — Kisah Mitos Dan Sains Di Lereng Gunung. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-13T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_19', 'Peta Harta Karun Banda Neira', 'Petualangan Rempah Dan Jejak Benteng Nassau', 'Petualangan Sejarah', 'Naskah "Peta Harta Karun Banda Neira" — Petualangan Rempah Dan Jejak Benteng Nassau. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-12T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_20', 'Seni Fokus Di Era Distraksi', 'Strategi Menjaga Atensi Dan Produktivitas', 'Pengembangan Diri', 'Naskah "Seni Fokus Di Era Distraksi" — Strategi Menjaga Atensi Dan Produktivitas. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-11T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_21', 'Jejak Sandi Di Keraton Ngayogyakarta', 'Misteri Lembaran Surat Utusan Belanda', 'Misteri & Detektif', 'Naskah "Jejak Sandi Di Keraton Ngayogyakarta" — Misteri Lembaran Surat Utusan Belanda. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-10T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_22', 'Sepiring Nasi Kucing Dan Mitos Kota', 'Etnografi Kuliner Angkringan Malam', 'Sosiologi & Budaya', 'Naskah "Sepiring Nasi Kucing Dan Mitos Kota" — Etnografi Kuliner Angkringan Malam. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-09T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_23', 'Jurnal Pengamatan Bintang Menoreh', 'Catatan Astronomi Amatir Di Ketinggian', 'Sains & Teknologi', 'Naskah "Jurnal Pengamatan Bintang Menoreh" — Catatan Astronomi Amatir Di Ketinggian. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-08T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_24', 'Melodi Terakhir Di Bangsal Srimimpi', 'Kisah Pemusik Keroncong Dan Kenangan Tua', 'Fiksi / Drama', 'Naskah "Melodi Terakhir Di Bangsal Srimimpi" — Kisah Pemusik Keroncong Dan Kenangan Tua. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-07T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_25', 'Bunga Kamboja Di Tepi Danau Toba', 'Kisah Romansa Dan Janji Di Tepi Air', 'Fiksi / Romansa', 'Naskah "Bunga Kamboja Di Tepi Danau Toba" — Kisah Romansa Dan Janji Di Tepi Air. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-06T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_26', 'Filosofi Batik Tulis & Garis Hidup', 'Simbolisme Motif Parang Dan Kawung', 'Sejarah & Kebudayaan', 'Naskah "Filosofi Batik Tulis & Garis Hidup" — Simbolisme Motif Parang Dan Kawung. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-05T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_27', 'Ekosistem Hutan Mangrove Pesisir', 'Riset Ketahanan Pantai Dan Keanekaragaman Hayati', 'Akademik & Riset', 'Naskah "Ekosistem Hutan Mangrove Pesisir" — Riset Ketahanan Pantai Dan Keanekaragaman Hayati. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-04T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_28', 'Catatan Harian Guru Di Pelosok Asmat', 'Perjuangan Literasi Di Tepian Sungai', 'Biografi & Memoar', 'Naskah "Catatan Harian Guru Di Pelosok Asmat" — Perjuangan Literasi Di Tepian Sungai. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-03T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_29', 'Misteri Manuskrip Daun Lontar Bali', 'Teka-Teki Aksara Kawi Yang Hilang', 'Misteri & Detektif', 'Naskah "Misteri Manuskrip Daun Lontar Bali" — Teka-Teki Aksara Kawi Yang Hilang. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-02T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_30', 'Algoritma Jiwa Dan Kesadaran Digital', 'Eksplorasi Filsafat Teknologi Masa Depan', 'Sains & Teknologi', 'Naskah "Algoritma Jiwa Dan Kesadaran Digital" — Eksplorasi Filsafat Teknologi Masa Depan. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-01T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_31', 'Kerajaan Air Di Lembah Bogowonto', 'Kisah Legenda Dan Penjaga Sungai', 'Fantasi & Folklor', 'Naskah "Kerajaan Air Di Lembah Bogowonto" — Kisah Legenda Dan Penjaga Sungai. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-30T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_32', 'Sketsa Kota Tua Batavia', 'Arsitektur Bangunan Kolonial Dan Restorasi', 'Sejarah & Kebudayaan', 'Naskah "Sketsa Kota Tua Batavia" — Arsitektur Bangunan Kolonial Dan Restorasi. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-29T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_33', 'Skripsi Lima Tahun Dan Kopi Dingin', 'Kisah Suka Duka Mahasiswa Tingkat Akhir', 'Komedi & Satir', 'Naskah "Skripsi Lima Tahun Dan Kopi Dingin" — Kisah Suka Duka Mahasiswa Tingkat Akhir. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-28T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_34', 'Jejak Perdagangan Rempah Di Maluku', 'Analisis Historis Jalur Pelayaran Nusantara', 'Sejarah & Kebudayaan', 'Naskah "Jejak Perdagangan Rempah Di Maluku" — Analisis Historis Jalur Pelayaran Nusantara. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-27T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_35', 'Rahasia Rumah Panggung Bugis', 'Kajian Konstruksi Kayu Dan Ketahanan Gempa', 'Akademik & Riset', 'Naskah "Rahasia Rumah Panggung Bugis" — Kajian Konstruksi Kayu Dan Ketahanan Gempa. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-26T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_36', 'Metode Penelitian Kualitatif Kritis', 'Panduan Praktis Untuk Mahasiswa Dan Peneliti', 'Akademik & Riset', 'Naskah "Metode Penelitian Kualitatif Kritis" — Panduan Praktis Untuk Mahasiswa Dan Peneliti. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-25T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_37', 'Harmoni Gong Dan Angklung Parahyangan', 'Pelestarian Seni Pertunjukan Tradisional', 'Sejarah & Kebudayaan', 'Naskah "Harmoni Gong Dan Angklung Parahyangan" — Pelestarian Seni Pertunjukan Tradisional. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-24T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_38', 'Melintasi Garis Khatulistiwa Pontianak', 'Catatan Perjalanan Di Tepian Sungai Kapuas', 'Biografi & Memoar', 'Naskah "Melintasi Garis Khatulistiwa Pontianak" — Catatan Perjalanan Di Tepian Sungai Kapuas. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-23T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_39', 'Kisah Pendaki Di Puncak Rinjani', 'Petualangan Persahabatan Dan Survival', 'Fiksi / Petualangan', 'Naskah "Kisah Pendaki Di Puncak Rinjani" — Petualangan Persahabatan Dan Survival. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-22T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_40', 'Komunikasi Interpersonal Di Era Siber', 'Dampak Media Sosial Terhadap Hubungan Manusia', 'Sosiologi & Budaya', 'Naskah "Komunikasi Interpersonal Di Era Siber" — Dampak Media Sosial Terhadap Hubungan Manusia. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-21T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_41', 'Senandung Hujan Di Lembah Harau', 'Kisah Pertemuan Dua Peneliti Geologi', 'Fiksi / Romansa', 'Naskah "Senandung Hujan Di Lembah Harau" — Kisah Pertemuan Dua Peneliti Geologi. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-20T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_42', 'Hukum Adat Dan Keadilan Pesisir', 'Kajian Normatif Kesepakatan Nelayan Lokal', 'Akademik & Riset', 'Naskah "Hukum Adat Dan Keadilan Pesisir" — Kajian Normatif Kesepakatan Nelayan Lokal. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-19T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_43', 'Bintang Fajar Di Atas Bukit Sikunir', 'Inspirasi Perjalanan Menemukan Impian', 'Pengembangan Diri', 'Naskah "Bintang Fajar Di Atas Bukit Sikunir" — Inspirasi Perjalanan Menemukan Impian. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-18T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_44', 'Antologi Cerita Rakyat Nusantara', 'Warisan Lisan Dari Sabang Sampai Merauke', 'Fantasi & Folklor', 'Naskah "Antologi Cerita Rakyat Nusantara" — Warisan Lisan Dari Sabang Sampai Merauke. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-17T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_45', 'Psikologi Menulis Dan Hambatan Kreatif', 'Memahami Pikiran Dan Alur Ide Penulis', 'Pengembangan Diri', 'Naskah "Psikologi Menulis Dan Hambatan Kreatif" — Memahami Pikiran Dan Alur Ide Penulis. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-16T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_46', 'Catatan Dokter Di Rumah Sakit Lapangan', 'Kisah Duka Dan Harapan Di Daerah Bencana', 'Biografi & Memoar', 'Naskah "Catatan Dokter Di Rumah Sakit Lapangan" — Kisah Duka Dan Harapan Di Daerah Bencana. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-15T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_47', 'Jejak Arsitektur Kolonial Di Surabaya', 'Penelusuran Bangunan Bersejarah Kota Pahlawan', 'Sejarah & Kebudayaan', 'Naskah "Jejak Arsitektur Kolonial Di Surabaya" — Penelusuran Bangunan Bersejarah Kota Pahlawan. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-14T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_48', 'Teka-Teki Di Perpustakaan Nasional', 'Investigasi Pencurian Dokumen Langka', 'Misteri & Detektif', 'Naskah "Teka-Teki Di Perpustakaan Nasional" — Investigasi Pencurian Dokumen Langka. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-13T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_49', 'Astronomi Tradisional Dan Pranata Mangsa', 'Kearifan Lokal Petani Jawa Menghitung Musim', 'Sains & Kebudayaan', 'Naskah "Astronomi Tradisional Dan Pranata Mangsa" — Kearifan Lokal Petani Jawa Menghitung Musim. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-12T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_50', 'Menemukan Makna Di Usia Dewasa Muda', 'Navigasi Karir Dan Kesehatan Mental', 'Pengembangan Diri', 'Naskah "Menemukan Makna Di Usia Dewasa Muda" — Navigasi Karir Dan Kesehatan Mental. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-11T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_51', 'Jejak Kereta Api Tua Jalur Bedono', 'Sejarah Lokomotif Uap Dan Jalur Bergigi', 'Sejarah & Kebudayaan', 'Naskah "Jejak Kereta Api Tua Jalur Bedono" — Sejarah Lokomotif Uap Dan Jalur Bergigi. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-10T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_52', 'Kopi Hujan Dan Kalimat Belum Selesai', 'Kumpulan Cerita Pendek Kehidupan', 'Fiksi / Prosa', 'Naskah "Kopi Hujan Dan Kalimat Belum Selesai" — Kumpulan Cerita Pendek Kehidupan. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-09T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_53', 'Etika Kedokteran Dan Masa Depan Bioteknologi', 'Analisis Kebijakan Kesehatan Modern', 'Akademik & Riset', 'Naskah "Etika Kedokteran Dan Masa Depan Bioteknologi" — Analisis Kebijakan Kesehatan Modern. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-08T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_54', 'Misteri Lonceng Kapal VOC Yang Hilang', 'Penyelidikan Artefak Laut Jawa', 'Misteri & Detektif', 'Naskah "Misteri Lonceng Kapal VOC Yang Hilang" — Penyelidikan Artefak Laut Jawa. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-07T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_55', 'Tata Kelola Kota Berkelanjutan', 'Strategi Ruang Hijau Dan Transportasi Publik', 'Akademik & Riset', 'Naskah "Tata Kelola Kota Berkelanjutan" — Strategi Ruang Hijau Dan Transportasi Publik. Dikembangkan secara kolaboratif oleh Bagus Setiawan bersama tim co-author Studio Buku.', '2026-09-06T00:00:00.000Z', 0, 'auth_3', 'Bagus Setiawan', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_56', 'Kumpulan Esai Kebudayaan Kontemporer', 'Refleksi Perubahan Sosial Dan Otentisitas', 'Sosiologi & Budaya', 'Naskah "Kumpulan Esai Kebudayaan Kontemporer" — Refleksi Perubahan Sosial Dan Otentisitas. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-05T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_57', 'Kisah Pengrajin Keramik Plered', 'Tradisi Gerabah Kayu Dan Daya Tahan Ekspor', 'Sejarah & Kebudayaan', 'Naskah "Kisah Pengrajin Keramik Plered" — Tradisi Gerabah Kayu Dan Daya Tahan Ekspor. Dikembangkan secara kolaboratif oleh Kirana Maharani bersama tim co-author Studio Buku.', '2026-09-04T00:00:00.000Z', 0, 'auth_2', 'Kirana Maharani', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_58', 'Menembus Kabut Gunung Bromo', 'Petualangan Fotografer Alam Di Kaldera', 'Petualangan', 'Naskah "Menembus Kabut Gunung Bromo" — Petualangan Fotografer Alam Di Kaldera. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-03T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_59', 'Sosiologi Pasar Tradisional Di Era Digital', 'Pergeseran Pola Transaksi Dan Ikatan Sosial', 'Sosiologi & Budaya', 'Naskah "Sosiologi Pasar Tradisional Di Era Digital" — Pergeseran Pola Transaksi Dan Ikatan Sosial. Dikembangkan secara kolaboratif oleh Siti Rahmania bersama tim co-author Studio Buku.', '2026-09-02T00:00:00.000Z', 0, 'auth_4', 'Siti Rahmania', '["Kirana Maharani","Bagus Setiawan"]');
INSERT OR REPLACE INTO projects (id, title, subtitle, genre, synopsis, createdAt, isPrivate, ownerId, ownerName, coAuthors) VALUES ('proj_60', 'Lorong Waktu Di Kampung Cyber Jogja', 'Novel Fiksi Spekulatif Teknologi Dan Tradisi', 'Fiksi / Spekulatif', 'Naskah "Lorong Waktu Di Kampung Cyber Jogja" — Novel Fiksi Spekulatif Teknologi Dan Tradisi. Dikembangkan secara kolaboratif oleh Rian Hidayat bersama tim co-author Studio Buku.', '2026-09-01T00:00:00.000Z', 0, 'auth_1', 'Rian Hidayat', '["Rian Hidayat","Siti Rahmania"]');
