export interface WriterTheme {
  id: string;
  name: string;
  tagline: string;
  badge: string;
  bgMain: string;
  bgCard: string;
  bgSidebar: string;
  bgHeader: string;
  bgIslandContainer: string;
  textMain: string;
  textMuted: string;
  border: string;
  accent: string;
  accentHover: string;
  accentText: string;
  editorPaperBg: string;
  editorPaperText: string;
  previewPaperBg: string;
  previewPaperText: string;
  isDark: boolean;
}

export const WRITER_THEMES: Record<string, WriterTheme> = {
  rosequartz: {
    id: "rosequartz",
    name: "Rose Quartz & Peony",
    tagline: "Estetika merah muda lembut, hangat & menginspirasi",
    badge: "🌸 Rose Quartz",
    bgMain: "bg-[#fdf4f5]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#f9e6e8]",
    bgHeader: "bg-[#33181d]",
    bgIslandContainer: "bg-[#4a242c]",
    textMain: "text-[#381a20]",
    textMuted: "text-[#855962]",
    border: "border-[#f2d0d5]",
    accent: "bg-[#db2777]",
    accentHover: "bg-[#be185d]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fffafb]",
    editorPaperText: "text-[#30161c]",
    previewPaperBg: "bg-[#f9ebee]",
    previewPaperText: "text-[#2d141b]",
    isDark: false,
  },
  matcha: {
    id: "matcha",
    name: "Matcha & Soft Ivory",
    tagline: "Aroma matcha hangat, tenang & menyejukkan",
    badge: "🍵 Matcha",
    bgMain: "bg-[#f4f7f1]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#e5eee0]",
    bgHeader: "bg-[#1b2b1a]",
    bgIslandContainer: "bg-[#2b3d2a]",
    textMain: "text-[#1c2e1b]",
    textMuted: "text-[#5a7358]",
    border: "border-[#d1e0d0]",
    accent: "bg-[#65a30d]",
    accentHover: "bg-[#4d7c0f]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fafcf9]",
    editorPaperText: "text-[#1a2b1a]",
    previewPaperBg: "bg-[#edf2e9]",
    previewPaperText: "text-[#1a2a1a]",
    isDark: false,
  },
  peach: {
    id: "peach",
    name: "Peach Blossom & Honey",
    tagline: "Kehangatan koral persik manis & cerah",
    badge: "🍑 Peach Blossom",
    bgMain: "bg-[#fff5f0]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#ffe6dc]",
    bgHeader: "bg-[#361c16]",
    bgIslandContainer: "bg-[#4e2920]",
    textMain: "text-[#3b1d16]",
    textMuted: "text-[#8a5d52]",
    border: "border-[#f7d3c6]",
    accent: "bg-[#f97316]",
    accentHover: "bg-[#ea580c]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fffaf7]",
    editorPaperText: "text-[#361a14]",
    previewPaperBg: "bg-[#fcebe4]",
    previewPaperText: "text-[#331812]",
    isDark: false,
  },
  lavender: {
    id: "lavender",
    name: "Mimpi Violet",
    tagline: "Ketenangan lembut lavender & ungu senja",
    badge: "💜 Lavender",
    bgMain: "bg-[#f5f2f9]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#e8e2f0]",
    bgHeader: "bg-[#201530]",
    bgIslandContainer: "bg-[#33234a]",
    textMain: "text-[#281c38]",
    textMuted: "text-[#6b5882]",
    border: "border-[#dcd4e8]",
    accent: "bg-[#7c3aed]",
    accentHover: "bg-[#6d28d9]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fcfaff]",
    editorPaperText: "text-[#261b36]",
    previewPaperBg: "bg-[#f3edf8]",
    previewPaperText: "text-[#251a36]",
    isDark: false,
  },
  velvet: {
    id: "velvet",
    name: "Velvet Orchid & Plum",
    tagline: "Mode gelap dramatis & elegan ungu malam",
    badge: "🩰 Velvet Plum",
    bgMain: "bg-[#18111e]",
    bgCard: "bg-[#241a2e]",
    bgSidebar: "bg-[#1f1528]",
    bgHeader: "bg-[#0f0a14]",
    bgIslandContainer: "bg-[#2f1f3b]",
    textMain: "text-[#f5edfd]",
    textMuted: "text-[#b39ebb]",
    border: "border-[#3a284a]",
    accent: "bg-[#ec4899]",
    accentHover: "bg-[#db2777]",
    accentText: "text-white",
    editorPaperBg: "bg-[#1d1425]",
    editorPaperText: "text-[#f1e6fc]",
    previewPaperBg: "bg-[#24192e]",
    previewPaperText: "text-[#f5edfd]",
    isDark: true,
  },
  sepia: {
    id: "sepia",
    name: "Kertas Sepia",
    tagline: "Klasik & hangat ala mesin tik tua",
    badge: "📜 Sepia",
    bgMain: "bg-[#f7f3e8]",
    bgCard: "bg-[#fffdf7]",
    bgSidebar: "bg-[#eee7d5]",
    bgHeader: "bg-[#2b2118]",
    bgIslandContainer: "bg-[#3d3024]",
    textMain: "text-[#2e2319]",
    textMuted: "text-[#7a6a57]",
    border: "border-[#e0d5c0]",
    accent: "bg-[#c46927]",
    accentHover: "bg-[#ab581d]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fdfaf2]",
    editorPaperText: "text-[#2a2118]",
    previewPaperBg: "bg-[#f8f2e4]",
    previewPaperText: "text-[#2a2016]",
    isDark: false,
  },
  sage: {
    id: "sage",
    name: "Hutan Tenang",
    tagline: "Sage green menenangkan untuk mata lelah",
    badge: "🌿 Sage",
    bgMain: "bg-[#f1f6f3]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#e1ece5]",
    bgHeader: "bg-[#142b20]",
    bgIslandContainer: "bg-[#214032]",
    textMain: "text-[#1a3327]",
    textMuted: "text-[#537565]",
    border: "border-[#cbe0d4]",
    accent: "bg-[#2d6a4f]",
    accentHover: "bg-[#22533e]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fbfdfc]",
    editorPaperText: "text-[#173024]",
    previewPaperBg: "bg-[#edf5f0]",
    previewPaperText: "text-[#183023]",
    isDark: false,
  },
  midnight: {
    id: "midnight",
    name: "Malam Pengarang",
    tagline: "Mode gelap lembut dengan aksen amber",
    badge: "🌙 Malam",
    bgMain: "bg-[#0b1329]",
    bgCard: "bg-[#17223b]",
    bgSidebar: "bg-[#111a2e]",
    bgHeader: "bg-[#070d1e]",
    bgIslandContainer: "bg-[#1e2d4d]",
    textMain: "text-[#f1f5f9]",
    textMuted: "text-[#94a3b8]",
    border: "border-[#273859]",
    accent: "bg-[#d97706]",
    accentHover: "bg-[#b45309]",
    accentText: "text-white",
    editorPaperBg: "bg-[#111c33]",
    editorPaperText: "text-[#e2e8f0]",
    previewPaperBg: "bg-[#17233d]",
    previewPaperText: "text-[#f1f5f9]",
    isDark: true,
  },
  terracotta: {
    id: "terracotta",
    name: "Senja & Kopi",
    tagline: "Suasana hangat kedai kopi sore hari",
    badge: "☕ Senja",
    bgMain: "bg-[#fcf5ef]",
    bgCard: "bg-[#ffffff]",
    bgSidebar: "bg-[#f2e5da]",
    bgHeader: "bg-[#2b1c16]",
    bgIslandContainer: "bg-[#3d2921]",
    textMain: "text-[#331f16]",
    textMuted: "text-[#7d5d4f]",
    border: "border-[#e6d4c7]",
    accent: "bg-[#d96b27]",
    accentHover: "bg-[#b85417]",
    accentText: "text-white",
    editorPaperBg: "bg-[#fffaf5]",
    editorPaperText: "text-[#301c13]",
    previewPaperBg: "bg-[#f9ece1]",
    previewPaperText: "text-[#2e1a12]",
    isDark: false,
  }
};
